/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class jni_impl_EBSJNI */

#ifndef _Included_jni_impl_EBSJNI
#define _Included_jni_impl_EBSJNI
#ifdef __cplusplus

extern "C" {

#endif


/*
 * Class:     jni_impl_EBSJNI
 * Method:    summ
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jni_1impl_EBSJNI_summ
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jni_impl_EBSJNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_1impl_EBSJNI_init
  (JNIEnv *, jobject);

/*
 * Class:     jni_impl_EBSJNI
 * Method:    checkFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_1impl_EBSJNI_checkFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
